version: '3'

services:
  db:
    container_name: db
    image: mysql:8.0.23
    platform: linux/x86_64
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./db_volume:/var/lib/mysql

  node:
    container_name: node
    build: .
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 3003:3003
    depends_on:
      - db
